# NUMPY TUTORIAL

In [1]:
import numpy as np

## THE BASICS

In [2]:
#CREATING A NUMPY ARRAY

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b = np.array([[9.0, 8.0, 7.0],[6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [5]:
  # Getting the dimensions of the array
   # an array can either be one, two or three dimensional
    #the format is (variable_name.ndim) 

In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [8]:
# getting the shape of the array
# the format is (variable_name.shape)
## NOTE: It prints out the result of shapes of arrays with this format (Roes,Columns)

In [9]:
a.shape
# this shows that a has a single dimension

(3,)

In [10]:
# This shows that b has 2 rows and 3 colums
b.shape

(2, 3)

In [11]:
# GETTING THE TYPE
a.dtype

dtype('int32')

In [12]:
# GETTING  THE SIZE
a.itemsize

4

In [13]:
#GETTING THE TOTAL SIZE
a.nbytes

12

# Accessing/Changing specific elements,rows,columns etc

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [15]:
a.shape

(2, 7)

In [16]:
# Getting a specific elemenet 
# the format is [r,c]

In [17]:
a[1,5]

13

In [18]:
# Getting a specific row

In [19]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
#Getting a specific column

In [21]:
a[:,4]

array([ 5, 12])

In [22]:
# Getting a little more fancy

In [23]:
a[0,1:6:2]

array([2, 4, 6])

In [24]:
# Changing an element

In [25]:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [26]:
a[:,2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

### 3 dimensional examples 

In [27]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# Getting speciofic elements

In [29]:
b[0,1,1]

4

In [30]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [31]:
 # Replacing elements

In [32]:
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

##### Initializing Different Types of Arrays

In [33]:
   # All Zeros matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((4,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [35]:
# ALl 1s matrix
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [36]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [37]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [38]:
# Random decimal numbers
np.random.rand(5,2)

array([[0.8060266 , 0.92285389],
       [0.13685364, 0.99977761],
       [0.25509788, 0.37825047],
       [0.37553346, 0.55493563],
       [0.46445395, 0.85720271]])

In [39]:
# random integer values
np.random.randint(5, size = (3,3))

array([[0, 3, 3],
       [0, 4, 3],
       [0, 3, 1]])

In [40]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# Create an array of ones
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
# Create an empty array
np.empty((3,2))


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
# Create a full array
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [44]:
# Create an array of evenly-spaced values
np.arange(10,25,5)

array([10, 15, 20])

In [45]:
# Create an array of evenly-spaced values
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [46]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
output[1:4,1:4] = z

In [50]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
output[2,2] = 9

In [52]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# MATHEMATICS

In [53]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [54]:
a + 2

array([3, 4, 5, 6])

In [55]:
a - 2

array([-1,  0,  1,  2])

In [56]:
a * 2

array([2, 4, 6, 8])

In [57]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [58]:
b = ([1,0,1,0])

In [59]:
a + b

array([2, 2, 4, 4])

In [60]:
# Take the sin of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [61]:
# Take the cos of all values
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [62]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,2,2],[3,3,3]])
z = np.array([1,2,3])

In [63]:
# Transpose of an array 

x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
# element wise addition

print(x + y)
print(np.add(x,y))

[[3 4 5]
 [7 8 9]]
[[3 4 5]
 [7 8 9]]


#### Linear Algebra

In [65]:
 a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
b = np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [67]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [68]:
# Find the determinant
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.linalg.det(c)

1.0

#### Statistcs

In [70]:
 stats = np.array([[1,2,3],[4,5,6]])
 stats                 

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.min(stats)

1

In [72]:
np.max(stats)

6

In [73]:
np.sum(stats)

21

### STACKING

In [74]:
# Vertically Stacking Vectors

In [75]:
v1 = [1,2,3,4]
v2 = [5,6,7,8]

np.vstack([v1,v2,v2,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [76]:
# Horizontal Stacking

In [77]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])